AZURE_API_KEY="YOUR-AZURE-SUBSCRIPTION-KEY"
FIREBASE_API_KEY= "YOUR-API-KEY"
WIT_ACCESS_TOKEN = "YOUR-WIT-CHATBOT-ACCESS-TOKEN"
FIREBASE_CONFIG = { ''' YOUR FIREBASE CONFIG OBJECT FOR YOUR WEB APP FROM FIREBASE '''}